# Generated by Django 3.2.8 on 2021-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('duration', models.IntegerField(default=0)),
                ('grade', models.CharField(max_length=256)),
            ],
        ),
    ]
