# Generated by Django 3.2.8 on 2021-11-03 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
