# Generated by Django 3.2.8 on 2021-11-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
