# Generated by Django 3.2.8 on 2021-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_remove_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=256),
        ),
    ]
