# Generated by Django 3.2.8 on 2021-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0013_auto_20211103_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.CharField(default='', max_length=256),
        ),
    ]
