# Generated by Django 3.2.8 on 2021-11-03 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0014_alter_movie_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.grade'),
        ),
    ]
